
title: ClubPoker
description: ClubPoker code documentation
theme: just-the-docs
google_analytics: G-C7PWLWSHB9

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  auto_ids: true

logo: /assets/images/icon128.png
repo_url: "https://github.com/jcook3701/ClubPoker"
repo_name: ClubPoker
nav_enabled: true
# search_enabled: true

# Exclude files/folders from Jekyll processing
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock

# Optional SEO metadata
seo:
  title: ClubPoker Documentation
  description: Full code documentation for the ClubPoker project
