
title: ClubPoker
description: ClubPoker code documentation
remote_theme: pmarsceill/just-the-docs
ga_tracking: "G-C7PWLWSHB9"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  auto_ids: true

logo: /assets/images/icon128.png
repo_name: ClubPoker
baseurl: "/ClubPoker"
repo_url: "https://github.com/jcook3701/ClubPoker"
nav_enabled: true
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "ClubPoker on GitHub":
    - "//github.com/jcook3701/ClubPoker"

carousel_images:
  - /assets/images/club-poker-screenshots/large-format/club-poker-calendar-page.jpg
  - /assets/images/club-poker-screenshots/large-format/club-poker-filters-page.jpg
  - /assets/images/club-poker-screenshots/large-format/club-poker-timezone-page.jpg

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Exclude files/folders from Jekyll processing
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock

# Optional SEO metadata
seo:
  title: ClubPoker Documentation
  description: Full code documentation for the ClubPoker project
